"""description in seed, year to ingegers

Revision ID: 02479753af13
Revises: 4d6a3e0be083
Create Date: 2024-07-09 21:52:53.572737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02479753af13'
down_revision = '4d6a3e0be083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('first_publish_year',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('first_publish_year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###
