"""Added f_name and l_name to user model

Revision ID: 028e9f516aa3
Revises: 7fd9fb850c68
Create Date: 2024-07-31 11:04:12.354629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028e9f516aa3'
down_revision = '7fd9fb850c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('l_name', sa.String(length=20), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('l_name')
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###
