"""trying to seed users

Revision ID: 798615d203d4
Revises: 02479753af13
Create Date: 2024-07-09 23:20:47.239691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798615d203d4'
down_revision = '02479753af13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
