"""added cover_id to Book model

Revision ID: f1f2679aceaf
Revises: 05e807641162
Create Date: 2024-07-09 15:36:54.594201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f2679aceaf'
down_revision = '05e807641162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', sa.Integer(), nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('cover_id')

    # ### end Alembic commands ###
